apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo.fullname" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "echo.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "echo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: echo
          image: {{ .Values.image }}
          command:
            - "-text nya"
          ports:
            - containerPort: 3000
      volumes:
        - name: {{ include "echo.fullname" . }}-configuration
          configMap:
            name: {{ include "echo.fullname" . }}-configuration